/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** サービスヘルスを取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description サービスプロセスが稼働しています。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
                /** @description 予期しないサーバーエラーが発生しました。 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 生存状態を取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description サービスプロセスが生存しています。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
                /** @description 予期しないサーバーエラーが発生しました。 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 受入可能状態を取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description サービスはリクエストを処理できます。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadinessResponse"];
                    };
                };
                /** @description 予期しないサーバーエラーが発生しました。 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description サービスはまだリクエストを処理できません。 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadinessResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/revision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 稼働中サーバーのリビジョンを取得する
         * @description Docker image build 時に FUKUROU_REVISION として焼き込まれた commit hash を text/plain で返します。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 稼働中 image の commit hash です。未指定の場合は unknown を返します。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
                /** @description 予期しないサーバーエラーが発生しました。 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluation/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 評価サマリーを取得する
         * @description closed trade の PF、勝率、期待 R、MAE/MFE、行動率、entry rate、相場局面別成績を返します。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 評価結果です。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EvaluationSummaryResponse"];
                    };
                };
                /** @description from / to の指定が不正です。 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 評価に必要な repository または外部依存が利用できません。 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluation/setups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * setup 別成績を取得する
         * @description setup tag 別の件数、PF、勝率、期待 R、MAE/MFE と、相場局面別の同指標を返します。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 評価結果です。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EvaluationSetupsResponse"];
                    };
                };
                /** @description from / to の指定が不正です。 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 評価に必要な repository または外部依存が利用できません。 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluation/calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 申告 p の較正を取得する
         * @description closed position に到達した ENTER decision を 0.1 幅 bin に分け、setup tag 別と LLM provider 別の実現勝率を返します。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 評価結果です。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EvaluationCalibrationResponse"];
                    };
                };
                /** @description from / to の指定が不正です。 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 評価に必要な repository または外部依存が利用できません。 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluation/benchmark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * benchmark 系列を取得する
         * @description buy & hold、no-trade、bot realized equity の日次系列と期間 return を返します。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 評価結果です。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EvaluationBenchmarkResponse"];
                    };
                };
                /** @description from / to の指定が不正です。 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 評価に必要な repository または外部依存が利用できません。 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluation/costs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * LLM cost と usage を取得する
         * @description runner phase audit に保存された Claude usage を集計し、usage 欠落 phase 数も返します。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 評価結果です。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EvaluationCostsResponse"];
                    };
                };
                /** @description from / to の指定が不正です。 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 評価に必要な repository または外部依存が利用できません。 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops/halt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 取引停止状態を設定する
         * @description SOFT_HALT または HARD_HALT を reason 付きで設定し、command_event_log に監査イベントを残します。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 停止 level と停止理由です。 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OpsHaltRequest"];
                };
            };
            responses: {
                /** @description 更新後の risk_state です。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OpsRiskStateResponse"];
                    };
                };
                /** @description request body または reason が不正です。 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description HARD_HALT 中に SOFT_HALT へ downgrade しようとしました。 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description risk_state command service が利用できません。 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 取引停止状態を解除する
         * @description SOFT_HALT または HARD_HALT を RUNNING へ戻し、手動再開理由を監査イベントへ残します。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 再開理由です。 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OpsResumeRequest"];
                };
            };
            responses: {
                /** @description 更新後の risk_state です。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OpsRiskStateResponse"];
                    };
                };
                /** @description request body または reason が不正です。 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description risk_state command service が利用できません。 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops/risk-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 取引停止状態を取得する
         * @description 現在の halt state、停止理由、再開時刻、drawdown ratio を返します。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 現在の risk_state です。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OpsRiskStateResponse"];
                    };
                };
                /** @description risk_state repository が利用できません。 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * LLM one-shot を手動起動する
         * @description reason 付きで MANUAL trigger の起動予約を取得し、runner を HTTP 応答後に非同期実行します。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 手動起動理由です。 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OpsTriggerRequest"];
                };
            };
            responses: {
                /** @description 起動予約を取得し、runner を非同期開始しました。 */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OpsTriggerResponse"];
                    };
                };
                /** @description request body または reason が不正です。 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 起動予約または停止状態により手動起動を拒否しました。 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description manual LLM launch service が利用できません。 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * paper account snapshot を取得する
         * @description paper ledger の account snapshot と更新時刻を返します。fake/demo 値は返しません。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description paper account snapshot です。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OpsAccountResponse"];
                    };
                };
                /** @description paper ledger repository が利用できません。 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * LLM decision の raw feed を取得する
         * @description 最新 decision を集計せずに新しい順で返します。limit は既定 20、最大 100 です。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description decision raw feed です。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OpsDecisionsResponse"];
                    };
                };
                /** @description limit が不正です。 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description decision repository が利用できません。 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * paper execution の raw feed を取得する
         * @description paper ledger の execution を新しい順で返します。limit は既定 20、最大 100 です。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description paper execution raw feed です。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OpsExecutionsResponse"];
                    };
                };
                /** @description limit が不正です。 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description paper ledger repository が利用できません。 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * open position と open order の raw feed を取得する
         * @description paper ledger の open position と open order を集計せずに返します。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description open position と open order の raw feed です。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OpsPositionsResponse"];
                    };
                };
                /** @description paper ledger repository が利用できません。 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * command_event_log の raw feed を取得する
         * @description 監査イベントを新しい順で返します。limit は既定 50、最大 200、eventType で任意に絞り込めます。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description audit raw feed です。 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OpsAuditResponse"];
                    };
                };
                /** @description limit または eventType が不正です。 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description command event feed reader が利用できません。 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HealthResponse */
        HealthResponse: {
            status: string;
            service?: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            message: string;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            status: string;
            lastReconciledAt?: string | null;
            lastMarketDataAt?: string | null;
        };
        /** EvaluationPeriodResponse */
        EvaluationPeriodResponse: {
            from: string;
            to: string;
            timezone: string;
        };
        /** EvaluationPerformanceResponse */
        EvaluationPerformanceResponse: {
            tradeCount: number;
            totalPnlJpy: string;
            profitFactor?: string | null;
            winRate?: string | null;
            expectedR?: string | null;
            averageMaeR?: string | null;
            averageMfeR?: string | null;
            rUnavailableCount: number;
            maeUnavailableCount: number;
            mfeUnavailableCount: number;
        };
        /** EvaluationKillCriterionResponse */
        EvaluationKillCriterionResponse: {
            closedTrades: number;
            currentProfitFactor?: string | null;
            minClosedTrades: number;
            minProfitFactor: string;
            remainingTrades: number;
            breached: boolean;
            hardHalt: boolean;
        };
        /** EvaluationActionCountResponse */
        EvaluationActionCountResponse: {
            action: string;
            count: number;
        };
        /** EvaluationRunRatesResponse */
        EvaluationRunRatesResponse: {
            decisionRunCount: number;
            actionCounts: components["schemas"]["EvaluationActionCountResponse"][];
            entryRate?: string | null;
            noTradeRate?: string | null;
        };
        /** EvaluationMarketRegimeResponse */
        EvaluationMarketRegimeResponse: {
            trend: string;
            volatility: string;
            performance: components["schemas"]["EvaluationPerformanceResponse"];
        };
        /** EvaluationSummaryResponse */
        EvaluationSummaryResponse: {
            period: components["schemas"]["EvaluationPeriodResponse"];
            truncated: boolean;
            performance: components["schemas"]["EvaluationPerformanceResponse"];
            killCriterion: components["schemas"]["EvaluationKillCriterionResponse"];
            runRates: components["schemas"]["EvaluationRunRatesResponse"];
            marketRegimes: components["schemas"]["EvaluationMarketRegimeResponse"][];
        };
        /** EvaluationSetupResponse */
        EvaluationSetupResponse: {
            setupTag: string;
            performance: components["schemas"]["EvaluationPerformanceResponse"];
        };
        /** EvaluationSetupsResponse */
        EvaluationSetupsResponse: {
            period: components["schemas"]["EvaluationPeriodResponse"];
            truncated: boolean;
            setups: components["schemas"]["EvaluationSetupResponse"][];
            marketRegimes: components["schemas"]["EvaluationMarketRegimeResponse"][];
        };
        /** EvaluationCalibrationBinResponse */
        EvaluationCalibrationBinResponse: {
            binIndex: number;
            lowerBoundInclusive: string;
            upperBoundInclusive: string;
            tradeCount: number;
            averageEstimatedProbability?: string | null;
            realizedWinRate?: string | null;
        };
        /** EvaluationCalibrationGroupResponse */
        EvaluationCalibrationGroupResponse: {
            groupKey: string;
            bins: components["schemas"]["EvaluationCalibrationBinResponse"][];
        };
        /** EvaluationCalibrationResponse */
        EvaluationCalibrationResponse: {
            period: components["schemas"]["EvaluationPeriodResponse"];
            truncated: boolean;
            bySetup: components["schemas"]["EvaluationCalibrationGroupResponse"][];
            byProvider: components["schemas"]["EvaluationCalibrationGroupResponse"][];
        };
        /** EvaluationBenchmarkPointResponse */
        EvaluationBenchmarkPointResponse: {
            date: string;
            buyAndHoldEquityJpy: string;
            noTradeEquityJpy: string;
            botEquityJpy: string;
        };
        /** EvaluationBenchmarkReturnResponse */
        EvaluationBenchmarkReturnResponse: {
            buyAndHoldReturn?: string | null;
            noTradeReturn?: string | null;
            botReturn?: string | null;
        };
        /** EvaluationBenchmarkResponse */
        EvaluationBenchmarkResponse: {
            period: components["schemas"]["EvaluationPeriodResponse"];
            assumptionsJa: string;
            baselineEquityJpy: string;
            points: components["schemas"]["EvaluationBenchmarkPointResponse"][];
            returns: components["schemas"]["EvaluationBenchmarkReturnResponse"];
        };
        /** EvaluationProviderCostResponse */
        EvaluationProviderCostResponse: {
            provider: string;
            totalCostUsd: string;
            phaseCount: number;
            missingUsagePhaseCount: number;
        };
        /** EvaluationModelTokenResponse */
        EvaluationModelTokenResponse: {
            model: string;
            inputTokens: number;
            outputTokens: number;
            cacheCreationInputTokens: number;
            cacheReadInputTokens: number;
        };
        /** EvaluationCostsResponse */
        EvaluationCostsResponse: {
            period: components["schemas"]["EvaluationPeriodResponse"];
            truncated: boolean;
            phaseCount: number;
            missingUsagePhaseCount: number;
            totalCostUsd: string;
            byProvider: components["schemas"]["EvaluationProviderCostResponse"][];
            byModel: components["schemas"]["EvaluationModelTokenResponse"][];
        };
        /** OpsHaltRequest */
        OpsHaltRequest: {
            /** @enum {string} */
            level: "SOFT" | "HARD";
            reason: string;
        };
        /** OpsRiskStateResponse */
        OpsRiskStateResponse: {
            state: string;
            haltReason?: string | null;
            haltAt?: string | null;
            resumedAt?: string | null;
            resumedReason?: string | null;
            drawdownRatio: string;
        };
        /** OpsResumeRequest */
        OpsResumeRequest: {
            reason: string;
        };
        /** OpsTriggerRequest */
        OpsTriggerRequest: {
            reason: string;
        };
        /** OpsTriggerResponse */
        OpsTriggerResponse: {
            invocationId: string;
            triggerKind: string;
        };
        /** OpsAccountResponse */
        OpsAccountResponse: {
            mode: string;
            cashJpy: string;
            initialCashJpy: string;
            btcQuantity: string;
            btcMarkPriceJpy: string;
            totalEquityJpy: string;
            equityPeakJpy: string;
            drawdownRatio: string;
            updatedAt: string;
        };
        /** OpsDecisionResponse */
        OpsDecisionResponse: {
            id: string;
            action: string;
            setupTags: string[];
            estimatedWinProbability: string;
            reasonJa: string;
            noTradeConditionsJa: string[];
            createdAt: string;
        };
        /** OpsDecisionsResponse */
        OpsDecisionsResponse: {
            decisions: components["schemas"]["OpsDecisionResponse"][];
        };
        /** OpsExecutionResponse */
        OpsExecutionResponse: {
            executionId: string;
            orderId?: string | null;
            positionId?: string | null;
            mode: string;
            symbol: string;
            side: string;
            priceJpy: string;
            sizeBtc: string;
            feeJpy: string;
            realizedPnlJpy: string;
            liquidity: string;
            executedAt: string;
        };
        /** OpsExecutionsResponse */
        OpsExecutionsResponse: {
            executions: components["schemas"]["OpsExecutionResponse"][];
        };
        /** Position */
        Position: {
            positionId: string;
            tradeGroupId: string;
            symbol: string;
            /** @enum {string} */
            mode: "PAPER" | "LIVE";
            /** @enum {string} */
            side: "LONG";
            /** @enum {string} */
            status: "OPEN" | "CLOSED";
            openedAt: string;
            closedAt?: string | null;
            sizeBtc: string;
            averageEntryPriceJpy: string;
            currentPriceJpy: string;
            currentStopLossJpy?: string | null;
            currentTakeProfitJpy?: string | null;
            unrealizedPnlJpy: string;
            unrealizedR: string;
            pyramidAddCount: number;
            highestPriceSinceEntryJpy: string;
            lowestPriceSinceEntryJpy?: string | null;
        };
        /** Order */
        Order: {
            orderId: string;
            intentId?: string | null;
            positionId?: string | null;
            tradeGroupId?: string | null;
            symbol: string;
            /** @enum {string} */
            mode: "PAPER" | "LIVE";
            /** @enum {string} */
            side: "BUY" | "SELL";
            /** @enum {string} */
            orderType: "MARKET" | "LIMIT" | "STOP";
            /** @enum {string} */
            status: "OPEN" | "PENDING_CANCEL" | "FILLED" | "CANCELED" | "REJECTED";
            sizeBtc: string;
            limitPriceJpy?: string | null;
            triggerPriceJpy?: string | null;
            protectiveStopPriceJpy?: string | null;
            takeProfitPriceJpy?: string | null;
            estimatedWinProbability?: string | null;
            reasonJa?: string | null;
            clientRequestId?: string | null;
            createdAt: string;
            updatedAt: string;
        };
        /** OpsPositionsResponse */
        OpsPositionsResponse: {
            positions: components["schemas"]["Position"][];
            openOrders: components["schemas"]["Order"][];
        };
        /** OpsAuditEventResponse */
        OpsAuditEventResponse: {
            id: string;
            eventType: string;
            toolName: string;
            payload: string;
            occurredAt: string;
        };
        /** OpsAuditResponse */
        OpsAuditResponse: {
            events: components["schemas"]["OpsAuditEventResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
